### ISSUE TITLE
[Question] What is the reason for downgrading the iOS version from 3.1 to 2.4?

### ISSUE THREAD

**Issue by gabn88** [Cloudoki/ImageDetectionCordovaPlugin#9]
Tracking the commits I saw that the iOS versions is downgraded, but I couldn't find an explanation.

Is OpenCV 3.1 not working on iOS? Or what is the reason?

**Comment by a31859** [comment]
When I started to make this plugin I was using OpenCV version 2.4. Later, due to a security issue with libjpeg I had to upgrade to version 3.1. This change worked fine in Android but for iOS the camera image capture was getting all back images. Since I need this quickly for that project I just reverted to OpenCV 2.4 and upgrade the libjpeg dependency.
